version: '3.1'

services:
  traefik:
    image: traefik
    ports:
      - "5913:80"
      - "8080:8080"
    volumes:
      - ./.traefik.toml:/etc/traefik/traefik.toml
      - ./logs:/logs

  replicated-docs:
    image: quay.io/replicated/replicated-docs:unstable
    volumes:
      - replicatedctl:/usr/src/docs/replicatedctl

  docs:
    build:
      context: .
      dockerfile: ./Dockerfiles/Dockerfile.hugo
    environment:
      - HUGO_WATCH=true
      - HUGO_BASEURL=http://localhost:5913/docs/
    volumes:
      - ./site:/src
      - ./docs:/src/content
      - ./hugo-config/docs.toml:/src/config.toml
      - replicatedctl:/src/content/reference/replicatedctl:ro
volumes:
  replicatedctl:
