baseurl = "https://www.replicated.com/docs/"
languageCode = "en-us"
title = "Replicated Documentation"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
googleAnalytics = "UA-61084834-1"

[taxonomies]
category = "categories"

[params]
  description = "Documentation and knowledgebase for Replicated."
  copyright = "Replicated, Inc."

  logo = "images/logo.png"
  favicon = ""
  pagetitle = "Replicated"
  permalink = "#"

  # Custom assets
  custom_css = []
  custom_js  = []
  pygmentsuseclasses = "false"
  pygmentscodefences = "true"

  # Syntax highlighting theme
  highlight_css  = ""

  docker_version_default = "1.11.2"
  docker_version_minimum = "1.7.1"
  replicated_api_version_current = "2.3.5"

  [params.palette]
  primary = "red"
  accent  = "light green"

  [params.font]
  text = "Ubuntu"
  code = "Ubuntu Mono"

[social]
  twitter = ""

[[menu.main]]
  name       = "Getting Started"
  url        = "getting-started"
  identifier = "/getting-started"
  weight     = 100

[[menu.main]]
  name       = "Packaging An Application"
  url        = "packaging-an-application"
  identifier = "/packaging-an-application"
  weight     = 200

[[menu.main]]
  name       = "Distributing An Application"
  url        = "distributing-an-application"
  identifier = "/distributing-an-application"
  weight     = 300

[[menu.main]]
  name       = "Examples"
  url        = "examples"
  identifier = "/examples"
  weight     = 400

[[menu.main]]
  name       = "Reference"
  url        = "reference"
  identifier = "/reference"
  weight     = 500

[[menu.main]]
  name       = "Knowledge Base"
  url        = "kb"
  identifier = "/kb"
  weight     = 600

[[menu.main]]
  name       = "Developer Resources"
  url        = "/docs/categories/developer-resources/"
  identifier = "/docs/categories/developer-resources/"
  weight     = 700

[[menu.main]]
  name       = "Supporting Your Customers"
  url        = "/docs/categories/supporting-your-customers/"
  identifier = "/docs/categories/supporting-your-customers/"
  weight     = 800

[blackfriday]
  smartypants	= true
  fractions = true
  smartDashes = true
  plainIDAnchors = true
